{{/*
ServiceAccount for the application
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
automountServiceAccountToken: false
