---
- name: 启动Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: 重启Docker
  systemd:
    name: docker
    state: restarted

- name: 重新加载Docker配置
  systemd:
    name: docker
    state: reloaded
